#!/usr/bin/env python3
"""Generate mosaic-runtime's codePointWidth table from Python's Unicode database.

Usage: python3.14 tools/generate-code-point-width.py > \
  mosaic-runtime/src/commonMain/kotlin/com/jakewharton/mosaic/text/codePointWidthTable.kt

Width 2: East_Asian_Width W or F (this includes emoji with default emoji presentation since
Unicode 9), plus the unassigned CJK ideograph planes which default to W.
Width 0: nonspacing and enclosing marks (Mn, Me), format characters (Cf) other than SOFT HYPHEN,
and Hangul Jamo medial vowels and final consonants, which combine with the preceding syllable.
"""
import sys
import unicodedata


def ranges(predicate):
    result = []
    start = None
    for cp in range(0x110000 + 1):
        inside = cp <= 0x10FFFF and predicate(cp)
        if inside and start is None:
            start = cp
        elif not inside and start is not None:
            result.append((start, cp - 1))
            start = None
    return result


def is_wide(cp):
    if 0x20000 <= cp <= 0x2FFFD or 0x30000 <= cp <= 0x3FFFD:
        return True
    return unicodedata.east_asian_width(chr(cp)) in ("W", "F")


def is_zero(cp):
    if cp == 0x00AD:
        return False
    if 0x1160 <= cp <= 0x11FF or 0xD7B0 <= cp <= 0xD7FF:
        return True
    return unicodedata.category(chr(cp)) in ("Mn", "Me", "Cf")


def table(name, rs):
    lines = [f"internal val {name} = intArrayOf("]
    for start, end in rs:
        lines.append(f"\t0x{start:X}, 0x{end:X},")
    lines.append(")")
    return "\n".join(lines)


print(f"""// Generated by tools/generate-code-point-width.py from Unicode {unicodedata.unidata_version}. Do not edit.
package com.jakewharton.mosaic.text

/** Inclusive start and end pairs of code points which occupy two cells. */
{table("WideCodePointRanges", ranges(is_wide))}

/** Inclusive start and end pairs of code points which occupy no cells. */
{table("ZeroWidthCodePointRanges", ranges(is_zero))}""")
